version: '3.8'

services:

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      USER_SERVICE_URL: http://user-service:5001
      RESTAURANT_SERVICE_URL: http://restaurant-service:5002
      ORDER_SERVICE_URL: http://order-service:5003
    depends_on:
      - user-service
      - restaurant-service
      - order-service

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "5001:5001"
    environment:
      PORT: 5001
      MONGO_URI: mongodb://mongo:27017/user-service-db
      JWT_SECRET: mysecretkey
    depends_on:
      - mongo

  restaurant-service:
    build:
      context: ./restaurant-service
    container_name: restaurant-service
    ports:
      - "5002:5002"
    environment:
      PORT: 5002
      MONGO_URI: mongodb://mongo:27017/restaurant-service-db
    depends_on:
      - mongo
      - rabbitmq

  order-service:
    build:
      context: ./order-service
    container_name: order-service
    ports:
      - "5003:5003"
    environment:
      PORT: 5003
      MONGO_URI: mongodb://mongo:27017/order-service-db
      RABBITMQ_URL: amqp://rabbitmq:5672
    depends_on:
      - mongo
      - rabbitmq

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mongo-data: