apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: {{ .Values.images.userService }}
        ports:
        - containerPort: {{ .Values.ports.userService }}
        env:
        - name: PORT
          value: "{{ .Values.ports.userService }}"
        - name: MONGO_URI
          value: "mongodb://mongo:27017/user-service-db"
        - name: JWT_SECRET
          value: "{{ .Values.env.jwtSecret }}"

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: user-service
  ports:
  - port: {{ .Values.ports.userService }}
    targetPort: {{ .Values.ports.userService }}